CREATE database yanolja;
use yanolja;

CREATE TABLE HIP_PLACE
(
  business_id   VARCHAR(50)     NOT NULL,
  name          VARCHAR(1024)     NOT NULL,
  address       VARCHAR(2048)   NOT NULL,
  city          VARCHAR(50)     NOT NULL,
  latitude      VARCHAR(50)     NOT NULL,
  longitude     VARCHAR(50)     NOT NULL
)
COMMENT ='Hip Place generated by spark-app';

CREATE TABLE REVIEWS
(
  business_id   VARCHAR(50)     NOT NULL,
  review        VARCHAR(8000)   NOT NULL,
  date          TIMESTAMP       NOT NULL
)
COMMENT ='Reviews generated by spark-app';

CREATE TABLE TIPS
(
  business_id   VARCHAR(50)     NOT NULL,
  tip           VARCHAR(8000)   NOT NULL,
  date          TIMESTAMP       NOT NULL
)
COMMENT ='Tips generated by spark-app';